### ISSUE TITLE
Elenasport.io API is shutting down

### ISSUE THREAD

**Issue by srseibs** [Breens-Mbaka/JetpackCompose-LiveScoreApp-MVVM#1]
https://elenasport.io reports that it is shutting down 1-Oct-2022 and no API calls will work at that point. 

That is devastating for this project. It would be awesome if you found another football API that would substitute; the entire UI should ideally be insulated from this. 

If you found another API, that would be an opportunity to further separate Model into Domain model, and the actual data returned from the API -- your existing project uses only one model for both purposes, which will cause the UI to have to change with a new API.

**Comment by Breens-Mbaka** [comment]
No worries will look for another API to substitute the Elena API before 1-Oct-2022

**Comment by Breens-Mbaka** [comment]
@srseibs Thanks for raising the issue I've managed to migrate to another API you can check the latest tutorial here on how to set it up https://youtu.be/uUX_TVwc_Pw. Also read README important info there
